# Generated by Django 3.0 on 2019-12-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TgUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=64)),
                ('username', models.CharField(max_length=64)),
                ('admin', models.BooleanField(blank=True)),
                ('tz_info', models.CharField(blank=True, max_length=5)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
