# Generated by Django 3.0 on 2019-12-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_userevents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userevents',
            name='remind_time',
            field=models.TimeField(blank=True, verbose_name='User Events'),
        ),
        migrations.AlterField(
            model_name='userevents',
            name='times',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='userevents',
            name='title',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
