# Generated by Django 3.0 on 2019-12-14 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_auto_20191214_1839'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserEvents',
            new_name='UserEvent',
        ),
    ]
