# Generated by Django 3.0 on 2019-12-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_auto_20191214_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='tz_info',
            field=models.CharField(blank=True, default='UTC+0', max_length=5),
        ),
    ]
