# Generated by Django 3.0 on 2019-12-15 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_auto_20191215_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='first_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='tz_info',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
