# Generated by Django 3.0 on 2019-12-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_auto_20191215_1641'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscriptions',
            new_name='Subscription',
        ),
        migrations.AlterField(
            model_name='tguser',
            name='first_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='tz_info',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
